###EschatologicalUnit.SpawnMobs配置文件###
#该插件为OurWorld服务器EschatologicalUnit小游戏项目的一个原创插件
#剧情插件

config:
    #本插件提示消息的前缀
    #注意：剧情消息不显示前缀
    prefix: "[EschatologicalUnit]"
    #显示每句剧情时需要延迟的时间(单位:秒)
    delayed: 1

data:
    Sentence:
        #消息ID
        Example:    #要显示的字符串,依次排序
            - "这是个&a例子1"
            - "这是个&b例子2"