###EschatologicalUnit.SpawnMobs配置文件###
#该插件为OurWorld服务器EschatologicalUnit小游戏项目的一个原创插件
#怪物生成插件

config:
    #本插件提示消息的前缀
    prefix: "[EschatologicalUnit]"


#关卡怪物配置
Wave:
  1:   #波数
  - MOB_A*5   #例如<怪物ID * 怪物数量>
  - MOB_B*15
  2:
  - MOB_A*10
  - MOB_B*10
  
#怪物配置
#例如  <怪物ID: 刷怪指令>
#刷怪指令中 %x% %y% %z% 会被替换成坐标
MOBs:
  MOB_A: summon zombie %x% %y% %z%
  MOB_B: summon witch %x% %y% %z%
  
#刷怪点配置
SpawnPoint:
  Ground1:  #刷怪点名称
    x: 0
    y: 0
    z: 0
  Ground2:
    x: 10
    y: 10
    z: 10
    
SpawnGroup:
  Group1:   #刷怪组名称
  - Ground1   #刷怪点名称
  Group2:
  - Ground1